# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: | 
           python calc.py
           python AddNum.py
        

  test:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: unit tests
          run: |
            python test_calc.py
            python test_AddNum.py         
        - name: Unit Testing With Python
  # You may pin to the exact commit or the version.
  # uses: PrajjawalBanati/Python-actions@a6d7420add2bf83557fec5ddf443f24f27e661fc
          uses: PrajjawalBanati/Python-actions@0.0.1
            
    # Always push your code and test case file as name.py and test_name.py
       
  deploy:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: deploy
          run: |
            python calc.py
            python AddNum.py
            
  code-coverage:
  
       runs-on: ubuntu-latest
       steps: 
         - name: Code Coverage Report
  # You may pin to the exact commit or the version.
  # uses: romeovs/lcov-reporter-action@90fd2b751de87c16edf5ae1d5878b73755c497b0
           uses: romeovs/lcov-reporter-action@v0.2.11
           with:
    # Github token
              github-token: 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
    # The location of the lcov.info file
              lcov-file: actions/checkout@v2
         
         
 
